export * from './house';
export * from './horarium';
export * from './poverty';
export * from './transfer';
export * from './obedience';
export * from './install';
export * from './week';
export * from './electorate';
export * from './chapter';
